//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitaxApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ankiety
    {
        public int AnkietyID { get; set; }
        public string Pytanie { get; set; }
        public int Ocena { get; set; }
        public int ProtokolyID { get; set; }
    
        public virtual Protokoly Protokoly { get; set; }
    }
}
