//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitaxApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hospitujacy
    {
        public int HospitujacyID { get; set; }
        public int ProwadzacyID { get; set; }
        public int ProtokolyID { get; set; }
    
        public virtual Protokoly Protokoly { get; set; }
        public virtual Prowadzacy Prowadzacy { get; set; }
    }
}
