//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitaxApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Protokoly
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Protokoly()
        {
            this.Ankieties = new HashSet<Ankiety>();
            this.Hospitujacies = new HashSet<Hospitujacy>();
            this.OcenySlownes = new HashSet<OcenySlowne>();
        }
    
        public int ProtokolyID { get; set; }
        public string Kurs { get; set; }
        public System.DateTime Data { get; set; }
        public int ProwadzacyID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ankiety> Ankieties { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hospitujacy> Hospitujacies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OcenySlowne> OcenySlownes { get; set; }
        public virtual Prowadzacy Prowadzacy { get; set; }
    }
}
